spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: 27612735czk
    url: jdbc:mysql://localhost:3306/ars?characterEncoding=utf-8&useSSL=false&serverTimezone=Asia/Shanghai
  redis:
    host: localhost
socket:
  host: 127.0.0.1
  port: 9007

logging:
  file:
    path: ./