spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: 123456
    url: jdbc:mysql://localhost:3306/ars?characterEncoding=utf-8&useSSL=false&serverTimezone=Asia/Shanghai
  redis:
    host: localhost
  mail:
    host: smtp.qq.com
    username:
    password:
    default-encoding: UTF-8
    port: 465
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
          ssl:
            enable: true
          required: true
logging:
  file:
    path: ./