mybatis:
  configuration:
    map-underscore-to-camel-case: true
    #控制台配置
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  mapper-locations: classpath:mapper/*.xml

server:
  port: 8080

socket:
  host: 127.0.0.1
  port: 9007
# 文件处理

media:
  dir: ./ArsMedia/

spring:
  main:
    allow-bean-definition-overriding: true
  data:
    neo4j:
      uri: bolt://8.136.211.96:7687
      username: neo4j
      password: 123456
  profiles:
    active: "@build.profile.id@"
  config:
    use-legacy-processing: true
  application:
    name: ars
  servlet:
    multipart:
      max-file-size: 16MB
      max-request-size: 16MB
  mail:
    host: smtp.qq.com
    username: XXXXXX@qq.com
    password: emailPassword
    default-encoding: UTF-8
    port: 465
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
          ssl:
            enable: true
          required: true
  mvc:
    static-path-pattern: /media/**
  web:
    resources:
      static-locations: classpath:/META-INF/resources/,classpath:/resources/,classpath:/static/,classpath:/public/,file:${media.dir}


  jpa:
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    show-sql: true
    hibernate:
      ddl-auto: update

